meta_product_name: "We Care"
meta_title: "We Care - Whatever happened, we're here, We Care."
meta_description: "We care is the first website that helps victims and witnesses for any criminal case in Belgium by providing them with a first-aid-kit."
meta_image: "fak.png" # should exist in `app/assets/images/`
